executor: slurm
jobs: 100
latency-wait: 60
rerun-incomplete: true
keep-going: true

default-resources:
  - slurm_account=jrigrp # replace with your slurm account
  - slurm_partition=high # replace with your slurm partition
  - mem_mb=48G
  - runtime=2880 # in minutes, 48 hours = 2880 minutes

set-resources:
  run_singer:
    cpus_per_task: 24
    mem_mb: 96G
    runtime: 2880
  run_polegon:
    mem_mb: 48G
    runtime: 2880
