executor: slurm
jobs: 100
latency-wait: 60
rerun-incomplete: true
keep-going: true

#slurm resources may need to be modified. 
default-resources:
  - slurm_account=account # replace with your slurm account name
  - slurm_partition=partition # replace with your slurm partition name
  - mem_mb=2000
  - runtime=1440 # in minutes, 24 hours 

set-resources:
  run_singer:
    cpus_per_task: 1
    mem_mb: 2000
    runtime: 1440
  run_polegon:
    mem_mb: 2000
    runtime: 1440
